# Turn on validation, so we can use import:
version: ~> 1.0

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

services:
- postgresql

env:
- SPEC_USER_TIME_ZONE=UTC

before_script:
- nvm install 13
- nvm use 13
- bundle exec rake db:schema:load
- bundle exec rails assets:precompile
- bundle exec rails assets:clean

script:
- APPMAP=true bundle exec rspec --format progress
