# Turn on validation, so we can use import:
version: ~> 1.0

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

addons:
  apt:
    packages:
    - parallel

services:
- postgresql

env:
- SPEC_USER_TIME_ZONE=UTC DB_NAME_TEST=pupilfirst_test

jobs:
  include:
  - stage: precompile
    workspaces:
      create:
        name: assets
        paths:
        - .graphql_ppx_cache/
        - .merlin
        - app/javascript/packages
        - docs/developers/node_modules/
        - lib/bs/
        - node_modules/
        - public/assets/
        - public/packs-test/
    before_script:
    - nvm install 13
    - nvm use 13
    script:
    - bundle exec rails assets:precompile
    - bundle exec rails assets:clean
    after_script:
    - true
  - stage: test
    workspaces:
      create:
        name: appmaps
        paths:
        - tmp/appmap
      use:
      - assets
    before_script:
    - nvm install 13
    - nvm use 13
    script:
    - bundle exec rails db:create db:schema:load
    - APPMAP=true bundle exec rspec -f doc || true
    after_script:
    - true
  - stage: upload
    workspaces:
      use:
      - appmaps
    install:
    - true
    script:
    - true
    

